# Generated by Django 5.1.4 on 2024-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default=1, help_text='Введите цену', max_length=20),
        ),
    ]
